version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...moving on...
  build:
    commands:
      - echo Build started on `date`
      - mvn test
      - echo Test completed on `date`
  post_build:
    commands:
      - mvn clean package
      - echo Build completed on `date`
artifacts:
  discard-paths: yes
  files:
    - target/*.jar
    - scripts/*
    - appspec.yml

